// 新增配方 DSL。每行：
// [id, zh, en, source, sourceNote, flavors, difficulty, method, glass, glassZh, liquid, abv, timeMin, ings[], customSteps?]
// ings: [ingredientId, qty, unit, role("required"|"optional"|"garnish")]
// method 决定默认步骤模板（摇和/搅拌/直调/捣压/分层）。
const R = "required", O = "optional", G = "garnish";
export const newRecipes = [
  /* ── IBA Unforgettables（规格表用量） ── */
  ["brandy-alexander","亚历山大","Brandy Alexander","iba","IBA 官方配方",["sweet"],2,"摇和","coupe","碟形杯","oklch(0.80 0.06 80)",24,4,
    [["cognac",30,"ml",R],["creme_de_cacao_white",30,"ml",R],["cream",30,"ml",R],["ice",0,"ml",O,"适量"]]],
  ["angel-face","天使之颜","Angel Face","iba","IBA 官方配方",["sweet","strong"],3,"搅拌","martini","马天尼杯","oklch(0.78 0.10 85)",32,4,
    [["gin",30,"ml",R],["apple_brandy",30,"ml",R],["apricot_liqueur",30,"ml",R],["ice",0,"ml",O,"适量"]]],
  ["aviation","飞行家","Aviation","iba","IBA 官方配方",["sour","fresh"],3,"摇和","martini","马天尼杯","oklch(0.75 0.08 95)",28,4,
    [["gin",45,"ml",R],["maraschino_liqueur",15,"ml",R],["lemon",15,"ml",R],["ice",0,"ml",O,"适量"]]],
  ["between-the-sheets","床笫之间","Between the Sheets","iba","IBA 官方配方",["sour","strong"],3,"摇和","martini","马天尼杯","oklch(0.76 0.09 70)",28,4,
    [["white_rum",30,"ml",R],["cognac",30,"ml",R],["orange_liqueur",30,"ml",R],["lemon",15,"ml",R],["ice",0,"ml",O,"适量"]]],
  ["casino","赌场","Casino","iba","IBA 官方配方",["sour","strong"],3,"摇和","martini","马天尼杯","oklch(0.78 0.08 90)",26,4,
    [["gin",40,"ml",R],["maraschino_liqueur",10,"ml",R],["lemon",20,"ml",R],["orange_bitters",2,"dash",R],["ice",0,"ml",O,"适量"]]],
  ["clover-club","三叶草俱乐部","Clover Club","iba","IBA 官方配方",["sour","fresh"],3,"摇和","coupe","碟形杯","oklch(0.66 0.14 10)",22,5,
    [["gin",45,"ml",R],["raspberry_syrup",15,"ml",R],["lemon",15,"ml",R],["egg_white",0.5,"个",O],["ice",0,"ml",O,"适量"]]],
  ["hanky-panky","翻云覆雨","Hanky Panky","iba","IBA 官方配方",["bitter","strong"],2,"搅拌","martini","马天尼杯","oklch(0.55 0.10 45)",30,4,
    [["gin",45,"ml",R],["sweet_vermouth",45,"ml",R],["fernet_branca",5,"ml",R],["ice",0,"ml",O,"适量"]]],
  ["john-collins","约翰柯林斯","John Collins","iba","IBA 官方配方",["sour","fresh"],2,"直调","highball","高球杯","oklch(0.80 0.08 90)",14,4,
    [["bourbon",45,"ml",R],["lemon",30,"ml",R],["simple_syrup",15,"ml",R],["soda",60,"ml",R],["ice",0,"ml",O,"适量"],["lemon",1,"片",G]]],
  ["last-word","遗言","Last Word","iba","IBA 官方配方",["sour","strong"],3,"摇和","coupe","碟形杯","oklch(0.75 0.10 130)",25,4,
    [["gin",22.5,"ml",R],["green_chartreuse",22.5,"ml",R],["maraschino_liqueur",22.5,"ml",R],["lime",22.5,"ml",R],["ice",0,"ml",O,"适量"]]],
  ["martinez","马丁内斯","Martinez","iba","IBA 官方配方",["sweet","strong"],2,"搅拌","martini","马天尼杯","oklch(0.62 0.11 55)",28,4,
    [["gin",45,"ml",R],["sweet_vermouth",45,"ml",R],["maraschino_liqueur",7.5,"ml",R],["aromatic_bitters",2,"dash",R],["ice",0,"ml",O,"适量"]]],
  ["mary-pickford","玛丽毕克馥","Mary Pickford","iba","IBA 官方配方",["sweet","fresh"],2,"摇和","martini","马天尼杯","oklch(0.68 0.14 25)",20,4,
    [["white_rum",45,"ml",R],["pineapple_juice",45,"ml",R],["grenadine",5,"ml",R],["maraschino_liqueur",5,"ml",R],["ice",0,"ml",O,"适量"]]],
  ["monkey-gland","猴腺","Monkey Gland","iba","IBA 官方配方",["sweet","fresh"],3,"摇和","martini","马天尼杯","oklch(0.70 0.13 55)",26,4,
    [["gin",50,"ml",R],["orange_juice",30,"ml",R],["grenadine",5,"ml",R],["absinthe",5,"ml",R],["ice",0,"ml",O,"适量"]]],
  ["paradise","乐园","Paradise","iba","IBA 官方配方",["sweet"],2,"摇和","martini","马天尼杯","oklch(0.74 0.11 75)",24,4,
    [["gin",35,"ml",R],["apricot_liqueur",20,"ml",R],["orange_juice",15,"ml",R],["ice",0,"ml",O,"适量"]]],
  ["planters-punch","种植者潘趣","Planter's Punch","iba","IBA 官方配方",["sweet","sour","fresh"],3,"摇和","highball","高球杯","oklch(0.62 0.15 40)",17,5,
    [["dark_rum",45,"ml",R],["orange_juice",35,"ml",R],["pineapple_juice",35,"ml",R],["lemon",20,"ml",R],["grenadine",10,"ml",R],["simple_syrup",10,"ml",R],["aromatic_bitters",3,"dash",R],["ice",0,"ml",O,"适量"]]],
  ["ramos-gin-fizz","拉莫斯金菲士","Ramos Gin Fizz","iba","IBA 官方配方",["sour","fresh"],4,"摇和","highball","高球杯","oklch(0.90 0.04 90)",14,7,
    [["gin",45,"ml",R],["lime",15,"ml",R],["lemon",15,"ml",R],["simple_syrup",30,"ml",R],["cream",60,"ml",R],["egg_white",1,"个",R],["orange_flower_water",3,"dash",R],["soda",30,"ml",O],["ice",0,"ml",O,"适量"]],
    [["备料与冰杯","高球杯加冰静置。所有材料称量备齐——这杯的秘诀是充分摇和。",null],
     ["先干摇","除苏打外全部材料入摇壶，不加冰先摇 30 秒让蛋清乳化。",null,30,"干摇乳化"],
     ["加冰久摇","加冰后继续摇和至少 1 分钟，直到摇壶外壁挂霜。",null,60,"久摇出绵密泡沫"],
     ["装杯","滤入杯中，缓缓注入苏打水托起泡沫，静置片刻再饮。",null]]],
  ["rusty-nail","锈钉","Rusty Nail","iba","IBA 官方配方",["sweet","strong"],1,"直调","rocks","古典杯","oklch(0.58 0.11 65)",32,3,
    [["blended_scotch",45,"ml",R],["drambuie",25,"ml",R],["ice",0,"ml",O,"适量"]]],
  ["sazerac","萨泽拉克","Sazerac","iba","IBA 官方配方",["strong","bitter"],4,"搅拌","rocks","古典杯","oklch(0.60 0.12 60)",35,5,
    [["cognac",50,"ml",R],["absinthe",10,"ml",R],["sugar_cube",1,"块",R],["peychaud_bitters",2,"dash",R],["ice",0,"ml",O,"适量"]],
    [["苦艾洗杯","冰过的古典杯倒入苦艾酒晃匀挂壁，多余弃去。",null],
     ["化糖","方糖滴裴乔苦精与少许水捣化。",null],
     ["搅拌","加入干邑与冰，搅拌约 20 秒。",null,20,"搅拌降温"],
     ["滤入","滤入挂好苦艾的杯中，可拧柠檬皮增香。",null]]],
  ["stinger","螫针","Stinger","iba","IBA 官方配方",["fresh","strong"],1,"搅拌","martini","马天尼杯","oklch(0.72 0.08 120)",30,3,
    [["cognac",50,"ml",R],["creme_de_menthe_white",20,"ml",R],["ice",0,"ml",O,"适量"]]],
  ["tuxedo","晚礼服","Tuxedo","iba","IBA 官方配方",["strong"],3,"搅拌","martini","马天尼杯","oklch(0.70 0.07 85)",30,4,
    [["gin",30,"ml",R],["dry_vermouth",30,"ml",R],["maraschino_liqueur",5,"ml",R],["absinthe",2.5,"ml",R],["orange_bitters",3,"dash",R],["ice",0,"ml",O,"适量"]]],
  ["vieux-carre","老广场","Vieux Carré","iba","IBA 官方配方",["strong","sweet"],3,"搅拌","rocks","古典杯","oklch(0.58 0.10 50)",30,4,
    [["rye",30,"ml",R],["cognac",30,"ml",R],["sweet_vermouth",30,"ml",R],["benedictine",10,"ml",R],["peychaud_bitters",2,"dash",R],["aromatic_bitters",2,"dash",R],["ice",0,"ml",O,"适量"]]],
  /* ── IBA Contemporary Classics ── */
  ["bellini","贝里尼","Bellini","iba","IBA 官方配方",["sweet","fresh"],1,"直调","coupe","笛形杯","oklch(0.78 0.10 55)",8,3,
    [["prosecco",100,"ml",R],["peach_puree",50,"ml",R]],
    [["果泥入杯","蜜桃果泥倒入冰过的笛形杯。",null],
     ["注入起泡酒","缓缓倒入普罗塞克，吧匙轻提拌匀，保留气泡。",null]]],
  ["black-russian","黑俄罗斯","Black Russian","iba","IBA 官方配方",["sweet","strong"],1,"直调","rocks","古典杯","oklch(0.35 0.05 40)",30,2,
    [["vodka",50,"ml",R],["coffee_liqueur",20,"ml",R],["ice",0,"ml",O,"适量"]]],
  ["bloody-mary","血腥玛丽","Bloody Mary","iba","IBA 官方配方",["sour","fresh"],3,"直调","highball","高球杯","oklch(0.55 0.16 35)",12,4,
    [["vodka",45,"ml",R],["tomato_juice",90,"ml",R],["lemon",15,"ml",R],["worcestershire_sauce",3,"dash",R],["tabasco",2,"dash",R],["salt",1,"撮",O],["ice",0,"ml",O,"适量"]],
    [["备料","高球杯加冰，柠檬榨汁备用。",null],
     ["组合","依次加入伏特加、番茄汁、柠檬汁、喼汁与辣酱。",null],
     ["调和","吧匙上下轻提混合，试味后补盐或辣酱。",null],
     ["装饰","以芹菜杆或柠檬角装饰（没有可省略）。",null]]],
  ["caipirinha","卡琵莉亚","Caipirinha","iba","IBA 官方配方",["sour","strong"],2,"捣压","rocks","古典杯","oklch(0.80 0.09 120)",24,4,
    [["cachaca",50,"ml",R],["lime",0.5,"个",R],["sugar_cube",2,"块",R],["ice",0,"ml",O,"碎冰适量"]],
    [["捣压","青柠切块入杯，放方糖捣压出汁。",null],
     ["加冰","碎冰加满。",null],
     ["倒酒","倒入卡莎萨，吧匙拌匀。",null]]],
  ["champagne-cocktail","香槟鸡尾酒","Champagne Cocktail","iba","IBA 官方配方",["bitter","strong"],2,"直调","coupe","笛形杯","oklch(0.82 0.07 85)",13,3,
    [["champagne",90,"ml",R],["sugar_cube",1,"块",R],["aromatic_bitters",2,"dash",R]],
    [["浸糖","方糖滴苦精浸透，放入笛形杯底。",null],
     ["注酒","缓缓注入冰镇香槟。",null]]],
  ["corpse-reviver-2","亡者复活 2 号","Corpse Reviver #2","iba","IBA 官方配方",["sour","strong"],3,"摇和","martini","马天尼杯","oklch(0.80 0.06 85)",25,4,
    [["gin",20,"ml",R],["orange_liqueur",20,"ml",R],["lillet_blanc",20,"ml",R],["lemon",20,"ml",R],["absinthe",1,"dash",R],["ice",0,"ml",O,"适量"]]],
  ["dark-n-stormy","黑暗风暴","Dark 'n' Stormy","iba","IBA 官方配方",["fresh","strong"],1,"直调","highball","高球杯","oklch(0.42 0.07 50)",18,3,
    [["dark_rum",60,"ml",R],["ginger_beer",100,"ml",R],["lime",1,"角",G],["ice",0,"ml",O,"适量"]],
    [["冰杯","高球杯加满冰。",null],
     ["注入姜汁啤酒","倒入姜汁啤酒。",null],
     ["浮朗姆","吧匙引流让黑朗姆浮在表面形成分层，青柠角装饰。",null]]],
  ["french-75","法式 75","French 75","iba","IBA 官方配方",["sour","fresh"],2,"摇和","coupe","笛形杯","oklch(0.84 0.06 85)",17,4,
    [["gin",30,"ml",R],["champagne",60,"ml",R],["lemon",15,"ml",R],["simple_syrup",10,"ml",R],["ice",0,"ml",O,"适量"]],
    [["摇和","金酒、柠檬汁与糖浆加冰摇和。",null,12,"摇和"],
     ["滤入","滤入冰过的笛形杯。",null],
     ["注入香槟","缓缓倒入香槟。",null]]],
  ["golden-cadillac","金色凯迪拉克","Golden Cadillac","iba","IBA 官方配方",["sweet"],2,"摇和","coupe","碟形杯","oklch(0.80 0.12 90)",21,4,
    [["galliano",30,"ml",R],["creme_de_cacao_white",30,"ml",R],["cream",30,"ml",R],["ice",0,"ml",O,"适量"]]],
  ["grasshopper","绿色蚱蜢","Grasshopper","iba","IBA 官方配方",["sweet"],1,"摇和","coupe","碟形杯","oklch(0.72 0.12 150)",20,4,
    [["creme_de_menthe_white",30,"ml",R],["creme_de_cacao_white",30,"ml",R],["cream",30,"ml",R],["ice",0,"ml",O,"适量"]]],
  ["harvey-wallbanger","哈维撞墙","Harvey Wallbanger","iba","IBA 官方配方",["sweet","fresh"],1,"直调","highball","高球杯","oklch(0.78 0.13 80)",12,3,
    [["vodka",40,"ml",R],["galliano",15,"ml",R],["orange_juice",90,"ml",R],["ice",0,"ml",O,"适量"]],
    [["冰杯","高球杯加冰。",null],
     ["伏特加与橙汁","倒入伏特加与橙汁，轻搅。",null],
     ["浮加利安奴","吧匙引流让加利安奴浮在表面。",null]]],
  ["hemingway-special","海明威特调","Hemingway Special","iba","IBA 官方配方",["sour","strong"],3,"摇和","coupe","碟形杯","oklch(0.76 0.09 60)",26,4,
    [["white_rum",60,"ml",R],["grapefruit_juice",40,"ml",R],["maraschino_liqueur",15,"ml",R],["lime",15,"ml",R],["ice",0,"ml",O,"适量"]]],
  ["horses-neck","马颈","Horse's Neck","iba","IBA 官方配方",["fresh","strong"],1,"直调","highball","高球杯","oklch(0.70 0.10 70)",16,3,
    [["cognac",40,"ml",R],["ginger_ale",120,"ml",R],["aromatic_bitters",2,"dash",R],["lemon",1,"片",G],["ice",0,"ml",O,"适量"]]],
  ["irish-coffee","爱尔兰咖啡","Irish Coffee","iba","IBA 官方配方",["sweet","strong"],2,"直调","highball","爱尔兰咖啡杯","oklch(0.40 0.05 45)",14,5,
    [["irish_whiskey",45,"ml",R],["hot_coffee",90,"ml",R],["simple_syrup",10,"ml",R],["cream",30,"ml",R]],
    [["温杯","热水温杯后倒掉。",null],
     ["组合","倒入威士忌、糖浆与热咖啡，搅匀。",null],
     ["浮奶油","吧匙背面引流，让微打发的淡奶油浮在表面。",null]]],
  ["kir","基尔","Kir","iba","IBA 官方配方",["sweet"],1,"直调","coupe","笛形杯","oklch(0.50 0.14 10)",11,2,
    [["white_wine",90,"ml",R],["creme_de_cassis",10,"ml",R]],
    [["利口酒入杯","黑加仑利口酒倒入冰过的笛形杯。",null],
     ["注入白葡萄酒","缓缓倒入干白，轻提拌匀。",null]]],
  ["long-island","长岛冰茶","Long Island Iced Tea","iba","IBA 官方配方",["sour","strong"],3,"直调","highball","高球杯","oklch(0.66 0.10 60)",22,5,
    [["vodka",15,"ml",R],["tequila",15,"ml",R],["white_rum",15,"ml",R],["gin",15,"ml",R],["orange_liqueur",15,"ml",R],["lemon",25,"ml",R],["simple_syrup",20,"ml",R],["cola",30,"ml",R],["ice",0,"ml",O,"适量"]],
    [["冰杯","高球杯加满冰。",null],
     ["五种酒","依次倒入伏特加、龙舌兰、白朗姆、金酒与橙味利口酒。",null],
     ["酸甜","加入柠檬汁与糖浆。",null],
     ["补可乐","可乐补满，吧匙轻提混合。",null]]],
  ["mai-tai","迈泰","Mai Tai","iba","IBA 官方配方",["sweet","sour"],3,"摇和","rocks","古典杯","oklch(0.70 0.12 65)",22,5,
    [["white_rum",30,"ml",R],["dark_rum",30,"ml",R],["orange_liqueur",15,"ml",R],["orgeat",15,"ml",R],["lime",30,"ml",R],["ice",0,"ml",O,"碎冰适量"],["mint",1,"枝",G]],
    [["摇和","白朗姆、橙味利口酒、杏仁糖浆与青柠汁加冰摇和。",null,12,"摇和"],
     ["装杯","古典杯加碎冰，滤入酒液。",null],
     ["浮黑朗姆","黑朗姆浮于表面，薄荷枝装饰。",null]]],
  ["mimosa","含羞草","Mimosa","iba","IBA 官方配方",["fresh","sweet"],1,"直调","coupe","笛形杯","oklch(0.82 0.11 80)",7,2,
    [["champagne",75,"ml",R],["orange_juice",75,"ml",R]],
    [["注入香槟","冰镇香槟先倒入笛形杯。",null],
     ["补橙汁","缓缓补入橙汁，不搅拌以保留气泡。",null]]],
  ["pina-colada","椰林飘香","Piña Colada","iba","IBA 官方配方",["sweet","fresh"],2,"摇和","highball","飓风杯","oklch(0.90 0.04 95)",13,4,
    [["white_rum",50,"ml",R],["coconut_cream",30,"ml",R],["pineapple_juice",50,"ml",R],["ice",0,"ml",O,"碎冰适量"]],
    [["摇和","全部材料加碎冰摇和至顺滑（有条件可用搅拌机打冰沙）。",null,12,"摇和"],
     ["装杯","倒入杯中，菠萝角或樱桃装饰（没有可省略）。",null]]],
  ["sea-breeze","海风","Sea Breeze","iba","IBA 官方配方",["sour","fresh"],1,"直调","highball","高球杯","oklch(0.62 0.14 20)",10,3,
    [["vodka",40,"ml",R],["cranberry_juice",80,"ml",R],["grapefruit_juice",30,"ml",R],["ice",0,"ml",O,"适量"]]],
  ["sex-on-the-beach","性感沙滩","Sex on the Beach","iba","IBA 官方配方",["sweet","fresh"],1,"直调","highball","高球杯","oklch(0.66 0.14 45)",10,3,
    [["vodka",40,"ml",R],["peach_schnapps",20,"ml",R],["orange_juice",40,"ml",R],["cranberry_juice",40,"ml",R],["ice",0,"ml",O,"适量"]]],
  ["singapore-sling","新加坡司令","Singapore Sling","iba","IBA 官方配方",["sweet","fresh"],4,"摇和","highball","高球杯","oklch(0.60 0.14 20)",16,5,
    [["gin",30,"ml",R],["cherry_liqueur",15,"ml",R],["benedictine",7.5,"ml",R],["pineapple_juice",120,"ml",R],["lime",15,"ml",R],["grenadine",10,"ml",R],["aromatic_bitters",1,"dash",R],["ice",0,"ml",O,"适量"]]],
  ["tequila-sunrise","龙舌兰日出","Tequila Sunrise","iba","IBA 官方配方",["sweet","fresh"],1,"直调","highball","高球杯","oklch(0.62 0.16 50)",11,3,
    [["tequila",45,"ml",R],["orange_juice",90,"ml",R],["grenadine",15,"ml",R],["ice",0,"ml",O,"适量"]],
    [["冰杯","高球杯加冰。",null],
     ["酒与橙汁","倒入龙舌兰与橙汁。",null],
     ["沉糖浆","沿杯壁缓缓倒入红石榴糖浆，沉底形成日出渐变，不搅拌。",null]]],
  ["vesper","维斯帕","Vesper","iba","IBA 官方配方",["strong"],3,"摇和","martini","马天尼杯","oklch(0.78 0.05 80)",33,4,
    [["gin",45,"ml",R],["vodka",15,"ml",R],["lillet_blanc",15,"ml",R],["ice",0,"ml",O,"适量"]]],
  ["kir-royale","皇家基尔","Kir Royale","classic","经典配方",["sweet"],1,"直调","coupe","笛形杯","oklch(0.48 0.15 5)",12,2,
    [["champagne",90,"ml",R],["creme_de_cassis",10,"ml",R]],
    [["利口酒入杯","黑加仑利口酒倒入冰过的笛形杯。",null],
     ["注入香槟","缓缓注入冰镇香槟。",null]]],
  ["white-russian","白俄罗斯","White Russian","iba","IBA 官方配方",["sweet"],1,"直调","rocks","古典杯","oklch(0.82 0.05 80)",20,3,
    [["vodka",50,"ml",R],["coffee_liqueur",20,"ml",R],["cream",30,"ml",R],["ice",0,"ml",O,"适量"]],
    [["冰杯","古典杯加冰。",null],
     ["酒与咖啡利口酒","倒入伏特加与咖啡利口酒。",null],
     ["浮奶油","吧匙引流让淡奶油浮在表面。",null]]],
  /* ── IBA New Era 与常见经典 ── */
  ["aperol-spritz","阿佩罗橙光","Aperol Spritz","iba","IBA 官方配方",["bitter","fresh"],1,"直调","coupe","葡萄酒杯","oklch(0.64 0.16 50)",11,3,
    [["prosecco",90,"ml",R],["aperol",60,"ml",R],["soda",30,"ml",R],["orange",1,"片",G],["ice",0,"ml",O,"适量"]],
    [["冰杯","大号葡萄酒杯加满冰。",null],
     ["组合","依次倒入普罗塞克、阿佩罗与苏打水。",null],
     ["装饰","轻搅一下，橙片装饰。",null]]],
  ["espresso-martini","浓缩咖啡马天尼","Espresso Martini","iba","IBA 官方配方",["bitter","strong"],2,"摇和","martini","马天尼杯","oklch(0.32 0.05 45)",22,4,
    [["vodka",40,"ml",R],["coffee_liqueur",20,"ml",R],["espresso",30,"ml",R],["simple_syrup",10,"ml",O],["ice",0,"ml",O,"适量"]],
    [["备咖啡","萃一份浓缩咖啡放凉备用。",null],
     ["摇和","全部材料加冰充分摇和，摇出咖啡油脂泡沫。",null,12,"摇和"],
     ["装杯","滤入冰过的马天尼杯，可放三颗咖啡豆装饰。",null]]],
  ["negroni-sbagliato","错版尼格罗尼","Negroni Sbagliato","iba","IBA 官方配方",["bitter"],1,"直调","rocks","古典杯","oklch(0.55 0.15 30)",12,3,
    [["prosecco",60,"ml",R],["campari",30,"ml",R],["sweet_vermouth",30,"ml",R],["orange",1,"片",G],["ice",0,"ml",O,"适量"]]],
  ["old-cuban","老古巴","Old Cuban","iba","IBA 官方配方",["sour","fresh"],3,"摇和","coupe","碟形杯","oklch(0.76 0.09 85)",18,5,
    [["gold_rum",45,"ml",R],["lime",22.5,"ml",R],["simple_syrup",30,"ml",R],["mint",6,"枝",R],["aromatic_bitters",2,"dash",R],["champagne",60,"ml",R],["ice",0,"ml",O,"适量"]],
    [["捣薄荷","薄荷与青柠汁、糖浆轻捣出香。",null],
     ["摇和","加朗姆酒与冰摇和，双重过滤入碟形杯。",null,12,"摇和"],
     ["注香槟","缓缓注入香槟。",null]]],
  ["paper-plane","纸飞机","Paper Plane","iba","IBA 官方配方",["bitter","sour"],2,"摇和","coupe","碟形杯","oklch(0.66 0.13 55)",24,4,
    [["bourbon",22.5,"ml",R],["amaro",22.5,"ml",R],["aperol",22.5,"ml",R],["lemon",22.5,"ml",R],["ice",0,"ml",O,"适量"]]],
  ["penicillin","盘尼西林","Penicillin","iba","IBA 官方配方",["sour","strong"],3,"摇和","rocks","古典杯","oklch(0.72 0.10 75)",26,5,
    [["blended_scotch",60,"ml",R],["lemon",22.5,"ml",R],["honey_syrup",22.5,"ml",R],["ginger",3,"片",R],["ice",0,"ml",O,"适量"]],
    [["捣姜","姜片入摇壶轻捣。",null],
     ["摇和","加威士忌、柠檬汁、蜂蜜糖浆与冰摇和。",null,12,"摇和"],
     ["装杯","双重过滤入加冰古典杯。",null]]],
  ["pisco-sour","皮斯科酸","Pisco Sour","iba","IBA 官方配方",["sour"],3,"摇和","coupe","碟形杯","oklch(0.86 0.05 90)",22,5,
    [["pisco",45,"ml",R],["lime",30,"ml",R],["simple_syrup",20,"ml",R],["egg_white",1,"个",O],["aromatic_bitters",1,"dash",G],["ice",0,"ml",O,"适量"]],
    [["干摇","皮斯科、青柠汁、糖浆与蛋清不加冰先摇 15 秒乳化。",null,15,"干摇"],
     ["加冰摇和","加冰再摇 12 秒。",null,12,"加冰摇和"],
     ["装杯","滤入杯中，表面滴苦精划花。",null]]],
  ["russian-spring-punch","俄罗斯之春潘趣","Russian Spring Punch","iba","IBA 官方配方",["sour","fresh"],2,"摇和","highball","高球杯","oklch(0.58 0.14 15)",14,4,
    [["vodka",25,"ml",R],["lemon",25,"ml",R],["creme_de_cassis",15,"ml",R],["simple_syrup",10,"ml",R],["champagne",60,"ml",R],["ice",0,"ml",O,"适量"]],
    [["摇和","伏特加、柠檬汁、黑加仑利口酒与糖浆加冰摇和。",null,12,"摇和"],
     ["装杯","滤入加冰高球杯。",null],
     ["注香槟","香槟补满。",null]]],
  ["southside","南边","Southside","classic","经典配方",["sour","fresh"],2,"摇和","coupe","碟形杯","oklch(0.78 0.08 130)",20,4,
    [["gin",60,"ml",R],["lime",30,"ml",R],["simple_syrup",15,"ml",R],["mint",5,"枝",R],["ice",0,"ml",O,"适量"]],
    [["捣薄荷","薄荷与糖浆、青柠汁轻捣。",null],
     ["摇和","加金酒与冰摇和。",null,12,"摇和"],
     ["装杯","双重过滤入冰过的碟形杯。",null]]],
  ["tipperary","蒂珀雷里","Tipperary","iba","IBA 官方配方",["strong","sweet"],2,"搅拌","martini","马天尼杯","oklch(0.60 0.10 60)",30,4,
    [["irish_whiskey",45,"ml",R],["sweet_vermouth",30,"ml",R],["green_chartreuse",15,"ml",R],["ice",0,"ml",O,"适量"]]],
  ["tommys-margarita","汤米玛格丽特","Tommy's Margarita","classic","经典配方",["sour","strong"],2,"摇和","rocks","古典杯","oklch(0.80 0.07 100)",28,4,
    [["tequila",60,"ml",R],["lime",30,"ml",R],["agave_syrup",15,"ml",R],["ice",0,"ml",O,"适量"],["salt",0,"撮",G,"杯口盐边（可选）"]]],
  ["naked-and-famous","一脱成名","Naked & Famous","iba","IBA 官方配方",["bitter","sour"],2,"摇和","coupe","碟形杯","oklch(0.66 0.13 60)",24,4,
    [["mezcal",22.5,"ml",R],["aperol",22.5,"ml",R],["yellow_chartreuse",22.5,"ml",R],["lime",22.5,"ml",R],["ice",0,"ml",O,"适量"]]],
  ["oaxaca-old-fashioned","瓦哈卡古典","Oaxaca Old Fashioned","classic","经典配方",["strong","sweet"],2,"搅拌","rocks","古典杯","oklch(0.64 0.10 70)",30,4,
    [["tequila",45,"ml",R],["mezcal",15,"ml",R],["agave_syrup",7.5,"ml",R],["aromatic_bitters",2,"dash",R],["orange",1,"片",G],["ice",0,"ml",O,"适量"]]],
  ["godfather","教父","Godfather","classic","经典配方",["sweet","strong"],1,"直调","rocks","古典杯","oklch(0.56 0.10 60)",30,3,
    [["blended_scotch",35,"ml",R],["amaretto",35,"ml",R],["ice",0,"ml",O,"适量"]]],
  ["godmother","教母","Godmother","classic","经典配方",["sweet","strong"],1,"直调","rocks","古典杯","oklch(0.68 0.10 65)",24,3,
    [["vodka",35,"ml",R],["amaretto",35,"ml",R],["ice",0,"ml",O,"适量"]]],
  ["kamikaze","神风","Kamikaze","classic","经典配方",["sour","strong"],1,"摇和","martini","马天尼杯","oklch(0.82 0.06 100)",24,3,
    [["vodka",30,"ml",R],["orange_liqueur",30,"ml",R],["lime",30,"ml",R],["ice",0,"ml",O,"适量"]]],
  ["woo-woo","呜呜","Woo Woo","classic","经典配方",["sweet","fresh"],1,"直调","highball","高球杯","oklch(0.60 0.15 15)",10,3,
    [["vodka",40,"ml",R],["peach_schnapps",20,"ml",R],["cranberry_juice",80,"ml",R],["ice",0,"ml",O,"适量"]]],
  ["blue-lagoon","蓝色泻湖","Blue Lagoon","classic","经典配方",["sweet","sour"],1,"直调","highball","高球杯","oklch(0.72 0.12 220)",13,3,
    [["vodka",30,"ml",R],["blue_curacao",20,"ml",R],["lemon",20,"ml",R],["soda",80,"ml",R],["ice",0,"ml",O,"适量"]]],
  ["b-52","B52 轰炸机","B-52","classic","经典配方",["sweet"],3,"分层","coupe","子弹杯","oklch(0.55 0.08 55)",22,4,
    [["coffee_liqueur",20,"ml",R],["irish_cream",20,"ml",R],["grand_marnier",20,"ml",R]],
    [["底层","咖啡利口酒倒入子弹杯。",null],
     ["中层","吧匙背面引流，缓缓注入爱尔兰奶油利口酒。",null],
     ["顶层","同样手法注入柑曼怡，形成清晰三层。",null]]],
  ["garibaldi","加里波第","Garibaldi","iba","IBA 官方配方",["bitter","fresh"],1,"直调","highball","高球杯","oklch(0.62 0.16 45)",9,3,
    [["campari",45,"ml",R],["orange_juice",135,"ml",R],["ice",0,"ml",O,"适量"],["orange",1,"片",G]]],
  ["jungle-bird","丛林鸟","Jungle Bird","classic","经典配方",["bitter","sweet"],2,"摇和","highball","高球杯","oklch(0.58 0.13 45)",16,4,
    [["dark_rum",45,"ml",R],["campari",22.5,"ml",R],["pineapple_juice",45,"ml",R],["lime",15,"ml",R],["simple_syrup",15,"ml",R],["ice",0,"ml",O,"适量"]]],
  ["lemon-drop","柠檬糖","Lemon Drop","classic","经典配方",["sour","sweet"],2,"摇和","martini","马天尼杯","oklch(0.84 0.12 95)",20,4,
    [["vodka",40,"ml",R],["orange_liqueur",15,"ml",R],["lemon",25,"ml",R],["simple_syrup",10,"ml",R],["ice",0,"ml",O,"适量"]]],
  ["yellow-bird","黄鸟","Yellow Bird","iba","IBA 官方配方",["sweet","fresh"],2,"摇和","martini","马天尼杯","oklch(0.80 0.12 90)",20,4,
    [["white_rum",30,"ml",R],["galliano",15,"ml",R],["orange_liqueur",15,"ml",R],["lime",15,"ml",R],["ice",0,"ml",O,"适量"]]],
  ["paloma","鸽子","Paloma","classic","经典配方（家庭做法：西柚汁加苏打替代西柚汽水）",["fresh","sour"],1,"直调","highball","高球杯","oklch(0.74 0.11 50)",12,3,
    [["tequila",50,"ml",R],["grapefruit_juice",50,"ml",R],["soda",50,"ml",R],["lime",15,"ml",R],["salt",0,"撮",G,"杯口盐边（可选）"],["ice",0,"ml",O,"适量"]]],
  ["bramble","荆棘","Bramble","classic","经典配方（黑莓利口酒常以黑加仑利口酒替代）",["sour","fresh"],2,"直调","rocks","古典杯","oklch(0.50 0.13 10)",18,4,
    [["gin",50,"ml",R],["lemon",25,"ml",R],["simple_syrup",12.5,"ml",R],["creme_de_cassis",15,"ml",R],["ice",0,"ml",O,"碎冰适量"]],
    [["组合","古典杯加碎冰，倒入金酒、柠檬汁与糖浆轻搅。",null],
     ["淋利口酒","黑加仑利口酒淋在表面形成渐变。",null]]]
];
